services:
  bkd-authcore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authcore-backend
    restart: always
    ports:
      - "8000:8000"
    
    # Crucial para resolver la DB si está en localhost del host (Linux)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      # Las variables se cargarán desde el .env automáticamente
    
    env_file:
      - .env

# Docker creará una red interna 'default' solo para este proyecto.
# El puerto 8000 queda abierto para que CUALQUIERA (incluido tu frontend) lo llame.