server {
    listen 80;
    server_name ${APP_DOMAIN}; # <--- Variable dinámica
    
    # Redirigir todo el tráfico HTTP a HTTPS automáticamente
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${APP_DOMAIN}; # <--- Variable dinámica

    # Rutas internas del contenedor para los certificados
    # (Estos nombres son fijos porque el script los genera con estos nombres)
    ssl_certificate /etc/ssl/certs/auth.pem;
    ssl_certificate_key /etc/ssl/certs/auth-key.pem;

    # Optimización de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # 'bkd-authcore' es el nombre del servicio en tu docker-compose.yml
        proxy_pass http://bkd-authcore:8000; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}